name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "10 * * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "admin@firstplato.com"
          git config --local user.name "ipang-dwi"
          git add -A
          
          arr[0]="feat: :tiger: auto commit"
          arr[1]="feat: :rabbit: auto commit"
          arr[2]="feat: :koala: auto commit"
          arr[3]="feat: :panda_face: auto commit"
          arr[4]="feat: :hamster: auto commit"
          arr[5]="feat: :cat: auto commit"
          arr[6]="feat: :penguin: auto commit"
          arr[7]="feat: :bear: auto commit"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
       
